debug: true
server:
  port: 8089
spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: net.sourceforge.jtds.jdbc.Driver
    url: jdbc:jtds:sqlserver://localhost:1433;databaseName=mservice_db;instance=SQLServer2014;
    username: rathish
    password: r@th15h
