eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
camunda:
  bpm:
    admin-user:
      id: rathish
      password: rathish123
spring:
  cloud:
    loadbalancer:
      cache:
        enabled: false
      ribbon:
        enabled: false