spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8070
  renewalPercentThreshold: 0.12
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    expected-client-renewal-interval-seconds:  3
    eviction-interval-timer-in-ms:  2000


management:
  endpoints:
    web:
      exposure:
        include: "*"

